name: art_of_evolve
description: "Art of Evolve: A holistic self-improvement application built with Flutter, focusing on goals, habits, and self-care."
publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.5.1
  cloud_firestore: ^5.0.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.0
  flutter_drawing_board: ^0.9.8
  flutter_local_notifications: ^17.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  home_widget: ^0.7.0
  image_picker: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.2
  record_windows: ^1.0.7
  riverpod_annotation: ^2.3.5
  timezone: any
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
